"""service_catalog_and_act_items

Revision ID: 6cd8b51a3e8b
Revises: 009
Create Date: 2026-04-07 19:34:06.831702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6cd8b51a3e8b'
down_revision: Union[str, None] = '009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('repair', 'maintenance', 'diagnostics', 'visit', 'other', name='service_category_enum'), nullable=False),
    sa.Column('unit', sa.Enum('pcs', 'hour', 'visit', 'kit', name='service_unit_enum'), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_catalog_code'), 'service_catalog', ['code'], unique=True)
    op.create_table('work_act_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_act_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('service', 'part', name='work_act_item_type_enum'), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['spare_parts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['service_catalog.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_act_id'], ['work_acts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('invoice_items', sa.Column('item_type', sa.Enum('service', 'part', 'manual', name='invoice_item_type_enum'), nullable=True))
    op.add_column('invoice_items', sa.Column('service_id', sa.Integer(), nullable=True))
    op.add_column('invoice_items', sa.Column('part_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoice_items', 'spare_parts', ['part_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'invoice_items', 'service_catalog', ['service_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.drop_column('invoice_items', 'part_id')
    op.drop_column('invoice_items', 'service_id')
    op.drop_column('invoice_items', 'item_type')
    op.drop_table('work_act_items')
    op.drop_index(op.f('ix_service_catalog_code'), table_name='service_catalog')
    op.drop_table('service_catalog')
    # ### end Alembic commands ###
